apps:
  - dvassallo/sillyface-games
  - repo: dvassallo/fullsend
    branch: master
    healthcheck: https://fullsend.game/up
  - repo: smallbets/userbase-homepage
    branch: master
    healthcheck: https://userbase.com/
