apps:
  - dvassallo/sillyface-games
  - repo: dvassallo/fullsend
    branch: master
    healthcheck: https://fullsend.game/up
  - repo: smallbets/userbase-homepage
    branch: master
    hosts:
      - userbase.com
      - www.userbase.com
      - userbase.dev
      - www.userbase.dev
    healthcheck: https://userbase.com/up
