apps:
  - acme/arcade-games
  - repo: acme/scoreboard
    branch: master
    healthcheck: https://scoreboard.example.com/up
  - repo: acme/marketing-site
    branch: master
    hosts:
      - marketing.example.com
      - www.marketing.example.com
      - marketing.example.net
      - www.marketing.example.net
    healthcheck: https://marketing.example.com/up
